[[changes]]
path = "items_game/items/8727"
# 使用三引号 (multiline string) 包裹 VDF 内容，可以完美保留换行和引号
content = """
			"name"		"Shattered Greatsword"
			"prefab"		"wearable"
			"creation_date"		"2015-01-30"
			"static_attributes"
			{
				"cannot craft"
				{
					"attribute_class"		"cannot_craft"
					"value"		"1"
				}
			}
			"image_inventory"		"econ/items/sven/shattered_greatsword/shattered_greatsword"
			"item_name"		"#DOTA_Item_Shattered_Greatsword"
			"item_rarity"		"mythical"
			"item_type_name"		"#DOTA_WearableType_Sword"
			"model_player"		"models/items/sven/shattered_greatsword/shattered_greatsword.vmdl"
			"particle_folder"		"particles/econ/items/sven/sven_shattered_great_sword"
			"portraits"
			{
				"icon"
				{
					"PortraitLightPosition"		"86.523247 -189.342712 251.034088"
					"PortraitLightAngles"		"55.711670 124.557495 0.000000"
					"PortraitLightFOV"		"50.000000"
					"PortraitLightDistance"		"212.000000"
					"PortraitLightColor"		"254 254 254"
					"PortraitShadowColor"		"97 97 97"
					"PortraitShadowScale"		"5.000000"
					"PortraitGroundShadowScale"		"1.500000"
					"PortraitAmbientColor"		"148 148 148"
					"PortraitAmbientScale"		"5.000000"
					"PortraitSpecularColor"		"251 74 84"
					"PortraitSpecularDirection"		"0.000000 0.000000 -1.000000"
					"PortraitSpecularPower"		"16.000000"
					"PortraitBackgroundColor1"		"0.000000 0.000000 0.200000"
					"PortraitBackgroundColor2"		"0.000000 0.000000 0.200000"
					"PortraitBackgroundColor3"		"0.600000 0.200000 0.000000"
					"PortraitBackgroundColor4"		"1.000000 0.100000 0.000000"
					"PortraitBackgroundTexture"		"materials/vgui/econ/item_icon_bg.vmat"
					"PortraitAnimationActivity"		"ACT_DOTA_ATTACK"
					"PortraitAnimationCycle"		"0.000000"
					"PortraitAnimationRate"		"0.000000"
					"PortraitHideHero"		"0"
					"PortraitLightScale"		"1.750000"
					"PortraitAmbientDirection"		"-0.850 75.650 30.680"
					"cameras"
					{
						"default"
						{
							"PortraitPosition"		"187.367569 32.806774 425.175934"
							"PortraitAngles"		"55.958862 220.468140 16.627808"
							"PortraitFOV"		"37.000000"
							"PortraitFar"		"1000.000000"
						}
					}
				}
			}
			"used_by_heroes"
			{
				"npc_dota_hero_sven"		"1"
			}
			"visuals"
			{
				"asset_modifier0"
				{
					"type"		"particle_create"
					"modifier"		"particles/econ/items/sven/sven_shattered_great_sword/sven_shattered_greatsword_ambient.vpcf"
				}
			}
"""

#[[changes]]
#path = "items_game/items/some_other_id"
#content = """
#"name" "Another Item"
#""" 